[package]
name = "escrow"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Gear Technologies"]

[dependencies]
gstd = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }
escrow-io = { path = "io" }
ft-main-io = { git = "https://github.com/gear-dapps/sharded-fungible-token.git", tag = "0.1.1" }
ft-logic-io = { git = "https://github.com/gear-dapps/sharded-fungible-token.git", tag = "0.1.1" }

[build-dependencies]
gear-wasm-builder = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }

[dev-dependencies]
gtest = { git = "https://github.com/gear-tech/gear.git", rev = "d4552434" }
gstd = { git = "https://github.com/gear-tech/gear.git", features = ["debug"], rev = "d4552434" }
