[package]
name = "escrow-io"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
gstd.workspace = true
gmeta = { workspace = true, features = ["codegen"] }
primitive-types.workspace = true
scale-info.workspace = true
parity-scale-codec.workspace = true
